import type { Product } from "./columns";

export const products: Product[] = [
  {
    sku: "ISH-001",
    name: "Industrial Safety Helmet Type II",
    category: "PPE",
    barcode: "8901234567890",
    barcodeType: "EAN-13",
    cost: 18.5,
    sellingPrice: 26.0,
    taxRate: 10,
    stock: 248,
    minStock: 20,
    maxStock: 500,
    reorderPoint: 50,
    leadTime: 7,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "CE-certified safety helmet, adjustable ratchet suspension, meets EN 397.",
    weight: 0.45,
    length: 28,
    width: 24,
    height: 20,
    supplier: "SafeGear Industries",
    supplierSku: "SG-ISH-002",
  },
  {
    sku: "PVC-020",
    name: "PVC Conduit 20mm x 3m",
    category: "Electrical",
    barcode: "8901234567891",
    barcodeType: "EAN-13",
    cost: 3.8,
    sellingPrice: 5.5,
    taxRate: 7,
    stock: 12,
    minStock: 30,
    maxStock: 200,
    reorderPoint: 40,
    leadTime: 5,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "20mm diameter PVC conduit, 3m length, grey, compliant with IEC 61386.",
    weight: 0.6,
    length: 300,
    width: 2.5,
    height: 2.5,
    supplier: "ElectroSupply Co.",
    supplierSku: "ES-PVC-020",
  },
  {
    sku: "WGL-001",
    name: "Work Gloves",
    category: "PPE",
    barcode: "8901234567892",
    barcodeType: "EAN-13",
    cost: 6.9,
    sellingPrice: 10.0,
    taxRate: 7,
    stock: 0,
    minStock: 50,
    maxStock: 300,
    reorderPoint: 60,
    leadTime: 10,
    shelfLife: 0,
    status: "Out of Stock",
    unit: "PAIR",
    description: "General purpose work gloves, reinforced palm, latex coating.",
    weight: 0.12,
    length: 28,
    width: 15,
    height: 3,
    supplier: "SafeGear Industries",
    supplierSku: "SG-WGL-001",
  },
  {
    sku: "BLT-010",
    name: "Hex Bolt M10 x 50mm",
    category: "Hardware",
    barcode: "8901234567893",
    barcodeType: "CODE128",
    cost: 0.35,
    sellingPrice: 0.6,
    taxRate: 7,
    stock: 560,
    minStock: 100,
    maxStock: 2000,
    reorderPoint: 200,
    leadTime: 3,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "Grade 8.8 zinc-plated hex bolt, M10 thread, 50mm length.",
    weight: 0.05,
    length: 5,
    width: 1.5,
    height: 1.5,
    supplier: "FastenTech Ltd.",
    supplierSku: "FT-M10-050",
  },
  {
    sku: "NUT-010",
    name: "Hex Nut M10",
    category: "Hardware",
    barcode: "8901234567894",
    barcodeType: "CODE128",
    cost: 0.12,
    sellingPrice: 0.25,
    taxRate: 7,
    stock: 35,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 300,
    leadTime: 3,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "Grade 8 zinc-plated hex nut, M10 thread.",
    weight: 0.01,
    length: 1.5,
    width: 1.5,
    height: 0.8,
    supplier: "FastenTech Ltd.",
    supplierSku: "FT-NUT-010",
  },
  {
    sku: "CAB-001",
    name: "Power Cable 2.5 sq.mm",
    category: "Electrical",
    barcode: "8901234567895",
    barcodeType: "EAN-13",
    cost: 24.5,
    sellingPrice: 35.0,
    taxRate: 7,
    stock: 9,
    minStock: 20,
    maxStock: 100,
    reorderPoint: 25,
    leadTime: 7,
    shelfLife: 0,
    status: "Low Stock",
    unit: "ROLL",
    description: "3-core PVC-insulated power cable, 2.5 sq.mm, 100m roll.",
    weight: 8.0,
    length: 100,
    width: 20,
    height: 20,
    supplier: "ElectroSupply Co.",
    supplierSku: "ES-CAB-2.5",
  },
  {
    sku: "TPE-001",
    name: "Packing Tape 48mm",
    category: "Packaging",
    barcode: "8901234567896",
    barcodeType: "EAN-13",
    cost: 1.95,
    sellingPrice: 3.0,
    taxRate: 7,
    stock: 120,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 80,
    leadTime: 2,
    shelfLife: 730,
    status: "Active",
    unit: "ROLL",
    description: "Clear BOPP packing tape, 48mm x 100m, strong adhesive.",
    weight: 0.18,
    length: 10,
    width: 5,
    height: 5,
    supplier: "PackRight Co.",
    supplierSku: "PR-TAPE-48",
  },
  {
    sku: "BOX-001",
    name: "Corrugated Box Large",
    category: "Packaging",
    barcode: "8901234567897",
    barcodeType: "EAN-13",
    cost: 2.75,
    sellingPrice: 4.5,
    taxRate: 7,
    stock: 18,
    minStock: 50,
    maxStock: 300,
    reorderPoint: 70,
    leadTime: 4,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "Double-wall corrugated box, 60 x 40 x 40 cm.",
    weight: 0.9,
    length: 60,
    width: 40,
    height: 40,
    supplier: "PackRight Co.",
    supplierSku: "PR-BOX-L",
  },
  {
    sku: "PAL-001",
    name: "Wooden Pallet",
    category: "Warehouse",
    barcode: "8901234567898",
    barcodeType: "CODE128",
    cost: 19.9,
    sellingPrice: 28.0,
    taxRate: 7,
    stock: 42,
    minStock: 20,
    maxStock: 150,
    reorderPoint: 30,
    leadTime: 5,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "Standard EUR-pallet (EPAL), 120 x 80 cm, heat-treated pine.",
    weight: 22.0,
    length: 120,
    width: 80,
    height: 14.4,
    supplier: "WoodWorks Supply",
    supplierSku: "WW-PAL-EUR",
  },
  {
    sku: "STR-001",
    name: "Stretch Film Roll",
    category: "Packaging",
    barcode: "8901234567899",
    barcodeType: "EAN-13",
    cost: 7.8,
    sellingPrice: 12.0,
    taxRate: 7,
    stock: 85,
    minStock: 30,
    maxStock: 200,
    reorderPoint: 40,
    leadTime: 3,
    shelfLife: 1095,
    status: "Active",
    unit: "ROLL",
    description: "LLDPE stretch film, 500mm x 300m, 23 micron.",
    weight: 3.5,
    length: 30,
    width: 10,
    height: 10,
    supplier: "PackRight Co.",
    supplierSku: "PR-STR-500",
  },
  {
    sku: "LAD-001",
    name: "Aluminum Ladder 6ft",
    category: "Tools",
    barcode: "8901234567900",
    barcodeType: "CODE128",
    cost: 59.9,
    sellingPrice: 85.0,
    taxRate: 10,
    stock: 6,
    minStock: 5,
    maxStock: 30,
    reorderPoint: 8,
    leadTime: 14,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "6-foot aluminum step ladder, 150kg capacity, non-slip steps.",
    weight: 5.2,
    length: 185,
    width: 56,
    height: 10,
    supplier: "ToolMart Intl.",
    supplierSku: "TM-LAD-6FT",
  },
  {
    sku: "HAM-001",
    name: "Claw Hammer",
    category: "Tools",
    barcode: "8901234567901",
    barcodeType: "EAN-13",
    cost: 12.5,
    sellingPrice: 18.0,
    taxRate: 7,
    stock: 45,
    minStock: 15,
    maxStock: 100,
    reorderPoint: 20,
    leadTime: 7,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "16oz steel claw hammer, fiberglass handle, magnetic nail starter.",
    weight: 0.68,
    length: 33,
    width: 8,
    height: 5,
    supplier: "ToolMart Intl.",
    supplierSku: "TM-HAM-16",
  },
  {
    sku: "DRL-001",
    name: "Cordless Drill 18V",
    category: "Tools",
    barcode: "8901234567902",
    barcodeType: "CODE128",
    cost: 95.0,
    sellingPrice: 135.0,
    taxRate: 10,
    stock: 14,
    minStock: 5,
    maxStock: 40,
    reorderPoint: 8,
    leadTime: 10,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "18V Li-ion cordless drill/driver, 13mm chuck, 2-speed gearbox, includes 2 batteries.",
    weight: 1.9,
    length: 25,
    width: 8,
    height: 22,
    supplier: "ToolMart Intl.",
    supplierSku: "TM-DRL-18V",
  },
  {
    sku: "MSK-001",
    name: "Dust Mask N95",
    category: "PPE",
    barcode: "8901234567903",
    barcodeType: "EAN-13",
    cost: 1.8,
    sellingPrice: 2.8,
    taxRate: 0,
    stock: 310,
    minStock: 100,
    maxStock: 1000,
    reorderPoint: 150,
    leadTime: 7,
    shelfLife: 1825,
    status: "Active",
    unit: "PCS",
    description: "NIOSH N95 respirator mask, adjustable nose clip, latex-free.",
    weight: 0.03,
    length: 15,
    width: 12,
    height: 1,
    supplier: "SafeGear Industries",
    supplierSku: "SG-MSK-N95",
  },
  {
    sku: "VST-001",
    name: "Reflective Safety Vest",
    category: "PPE",
    barcode: "8901234567904",
    barcodeType: "EAN-13",
    cost: 8.4,
    sellingPrice: 13.0,
    taxRate: 7,
    stock: 0,
    minStock: 30,
    maxStock: 200,
    reorderPoint: 40,
    leadTime: 10,
    shelfLife: 0,
    status: "Out of Stock",
    unit: "PCS",
    description: "Hi-vis orange safety vest with 2 silver reflective bands, EN ISO 20471 Class 2.",
    weight: 0.2,
    length: 65,
    width: 58,
    height: 1,
    supplier: "SafeGear Industries",
    supplierSku: "SG-VST-ORG",
  },
  {
    sku: "FRK-001",
    name: "Forklift Battery Charger",
    category: "Warehouse",
    barcode: "8901234567905",
    barcodeType: "CODE128",
    cost: 420.0,
    sellingPrice: 580.0,
    taxRate: 10,
    stock: 2,
    minStock: 1,
    maxStock: 10,
    reorderPoint: 2,
    leadTime: 21,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "24V/30A automatic forklift battery charger, 3-stage charging, LCD display.",
    weight: 12.0,
    length: 35,
    width: 28,
    height: 22,
    supplier: "PowerTech Solutions",
    supplierSku: "PT-CHG-24V30",
  },
  {
    sku: "LBL-001",
    name: "Thermal Label 100x150mm",
    category: "Label",
    barcode: "8901234567906",
    barcodeType: "EAN-13",
    cost: 9.5,
    sellingPrice: 14.0,
    taxRate: 7,
    stock: 160,
    minStock: 50,
    maxStock: 400,
    reorderPoint: 70,
    leadTime: 5,
    shelfLife: 1095,
    status: "Active",
    unit: "ROLL",
    description: "Direct thermal label 100x150mm, 350 labels/roll, perforated, for shipping.",
    weight: 0.35,
    length: 15,
    width: 12,
    height: 12,
    supplier: "LabelPro Asia",
    supplierSku: "LP-100x150",
  },
  {
    sku: "SCN-001",
    name: "Wireless Barcode Scanner",
    category: "Equipment",
    barcode: "8901234567907",
    barcodeType: "CODE128",
    cost: 135.0,
    sellingPrice: 190.0,
    taxRate: 10,
    stock: 8,
    minStock: 3,
    maxStock: 20,
    reorderPoint: 5,
    leadTime: 14,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "2.4GHz wireless 1D/2D barcode scanner, USB receiver, 100m range, rechargeable.",
    weight: 0.22,
    length: 18,
    width: 6,
    height: 8,
    supplier: "TechScan Ltd.",
    supplierSku: "TS-SCN-2D",
  },
  {
    sku: "RCK-001",
    name: "Heavy Duty Rack Beam",
    category: "Warehouse",
    barcode: "8901234567908",
    barcodeType: "CODE128",
    cost: 45.5,
    sellingPrice: 65.0,
    taxRate: 7,
    stock: 28,
    minStock: 10,
    maxStock: 80,
    reorderPoint: 15,
    leadTime: 10,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "Teardrop pallet rack beam, 2700mm, capacity 1500kg/pair, safety lock.",
    weight: 11.0,
    length: 270,
    width: 5,
    height: 11,
    supplier: "RackSystems Co.",
    supplierSku: "RS-BEAM-270",
  },
  {
    sku: "PNT-001",
    name: "Industrial Paint White 5L",
    category: "Maintenance",
    barcode: "8901234567909",
    barcodeType: "EAN-13",
    cost: 29.9,
    sellingPrice: 42.0,
    taxRate: 7,
    stock: 0,
    minStock: 10,
    maxStock: 60,
    reorderPoint: 15,
    leadTime: 7,
    shelfLife: 730,
    status: "Out of Stock",
    unit: "CAN",
    description: "Water-based industrial floor paint, white, anti-slip additive, 5L.",
    weight: 5.8,
    length: 22,
    width: 22,
    height: 26,
    supplier: "ChemCoat Industries",
    supplierSku: "CC-PNT-W5L",
  },
];
