import type { Product } from "./types";

export const products: Product[] = [
  {
    sku: "ISH-001",
    name: "Industrial Safety Helmet Type II",
    category: "PPE",
    barcode: "8901234567890",
    barcodeType: "EAN-13",
    cost: 18.5,
    sellingPrice: 26.0,
    taxRate: 10,
    stock: 248,
    minStock: 20,
    maxStock: 500,
    reorderPoint: 50,
    leadTime: 7,
    shelfLife: 0,
    status: "Active",
    unit: "PCS",
    description: "CE-certified safety helmet, adjustable ratchet suspension, meets EN 397.",
    weight: 0.45,
    length: 28,
    width: 24,
    height: 20,
    supplier: "SafeGear Industries",
    supplierSku: "SG-ISH-002",
    _id: "1"
  },
  {
    sku: "PVC-020",
    name: "PVC Conduit 20mm x 3m",
    category: "Electrical",
    barcode: "8901234567891",
    barcodeType: "EAN-13",
    cost: 3.8,
    sellingPrice: 5.5,
    taxRate: 7,
    stock: 12,
    minStock: 30,
    maxStock: 200,
    reorderPoint: 40,
    leadTime: 5,
    shelfLife: 0,
    status: "Low Stock",
    unit: "PCS",
    description: "20mm diameter PVC conduit, 3m length, grey, compliant with IEC 61386.",
    weight: 0.6,
    length: 300,
    width: 2.5,
    height: 2.5,
    supplier: "ElectroSupply Co.",
    supplierSku: "ES-PVC-020",
     _id: "2"
  }
]